name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Brew Update
      run: brew update
    - name: Brew Install
      run: brew install ninja
    - name: Get Depot Tools
      run: git clone https://github.com/Kode/depot_tools.git
    - name: Add Depot Tools to the path
      run: echo "./depot_tools" >> $GITHUB_PATH
    - name: Bootstrap gclient configuration
      run: cp standalone.gclient .gclient
    - name: Sync gclient
      run: gclient sync
    - name: Compile
      run: mkdir -p out/Release && cd out/Release && cmake -DCMAKE_BUILD_TYPE=Release -GNinja ../.. && ninja
