name: Windows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Get Depot Tools
      run: git clone git@github.com:Kode/depot_tools.git
    - name: Add Depot Tools to the path
      run: Add-Content $env:GITHUB_PATH ".\depot_tools"
    - name: Bootstrap gclient configuration
      run: cp standalone.gclient .gclient
    - name: Sync gclient
      run: gclient sync
    - name: Compile
      run: mkdir -p out\Debug && cd out\Debug && cmake -GNinja ../.. && ninja
